from typing import Union

class Foo:
    def __mod__(self, other: Union[Foo, str]) -> Foo: ...
    def __rmod__(self, other: str) -> Foo: ...

from typing import Union

class Foo:
    def __mul__(self, other: Union[Foo, str]) -> Foo: ...
    def __rmul__(self, other: str) -> Foo: ...

from typing import Union

class Foo:
    def __mod__(self, other: Union[Foo, int]) -> Foo: ...
    def __rmod__(self, other: int) -> Foo: ...

from typing import Union
 
class Foo:
    def __mod__(self, other: Union[Foo, str]) -> Foo: ...          
    def __rmod__(self, other: str): ...          

from typing import Union
 
class Foo:
    def __mod__(self, other: Union[Foo, str]) -> int: ...   
    def __rmod__(self, other: str) -> int: ...   
