from dataclasses import dataclass

@dataclass(order=True)
class Dummy:
    foo: str
    bar: int

from typing import Any

class Dummy:
    foo: str
    bar: int
    def __init__(self, foo: Any, bar: Any) -> None: ...
    def __lt__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...

class Dummy:
    foo: str
    bar: int
    def __init__(self, foo: str, bar: bar) -> None: ...
    def __lt__(self, other: Dummy) -> bool: ...
    def __gt__(self, other: Dummy) -> bool: ...
    def __le__(self, other: Dummy) -> bool: ...
    def __ge__(self, other: Dummy) -> bool: ...
